In [10]:
#Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
#Improve visualization
sns.set_style("whitegrid")

# Load Dataset

In [11]:
df = pd.read_csv(
    r"E:\End to end sales data project\Data\Sample - superstore.csv",
    encoding='ISO-8859-1'
)

In [12]:
df.head(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.0,6.8714

In [24]:
#OVERVIEW

print("Dataset Overview")
print("="*60)

print(f"\nDataset Shape: {df.shape}")
print(f"Total Rows: {df.shape[0]:,}")
print(f"Total Columns: {df.shape[1]}")

print("\nColumn Names:")
print(df.columns.tolist())

Dataset Overview
============================================================

Dataset Shape: (9994, 29)
Total Rows: 9,994
Total Columns: 29

Column Names:
['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit', 'Order_Year', 'Order_Month', 'Order_Month_Name', 'Order_Quarter', 'Order_Day', 'Shipping_Days', 'Profit_Margin', 'Is_Profitable']

In [25]:
#Column Information
print("Column Information")
print("="*60)

df.info()

Column Information
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 29 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Row ID            9994 non-null   int64
 1   Order ID          9994 non-null   object
 2   Order Date        9994 non-null   datetime64[ns]
 3   Ship Date         9994 non-null   datetime64[ns]
 4   Ship Mode         9994 non-null   object
 5   Customer ID       9994 non-null   object
 6   Customer Name     9994 non-null   object
 7   Segment           9994 non-null   object
 8   Country           9994 non-null   object
 9   City              9994 non-null   object
 10  State             9994 non-null   object
 11  Postal Code       9994 non-null   int64
 12  Region            9994 non-null   object
 13  Product ID        9994 non-null   object
 14  Category          9994 non-null   object
 15  Sub-Category      9994 non-null   object
 16  Product Name      9994 non-null   object
 17  Sales             9994 non-null   float64
 18  Quantity          9994 non-null   int64
 19  Discount          9994 non-null   float64
 20  Profit            9994 non-null   float64
 21  Order_Year        9994 non-null   int32
 22  Order_Month       9994 non-null   int32
 23  Order_Month_Name  9994 non-null   object
 24  Order_Quarter     9994 non-null   int32
 25  Order_Day         9994 non-null   object
 26  Shipping_Days     9994 non-null   int64
 27  Profit_Margin     9994 non-null   float64
 28  Is_Profitable     9994 non-null   bool
dtypes: bool(1), datetime64[ns](2), float64(4), int32(3), int64(4), object(15)
memory usage: 2.0+ MB

In [26]:
print("Descriptive Staticstics")
print("="*60)

df.describe()

Descriptive Staticstics
============================================================

,Row ID,Order Date,Ship Date,Postal Code,Sales,Quantity,Discount,Profit,Order_Year,Order_Month,Order_Quarter,Shipping_Days,Profit_Margin
count,9994.000000,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,2016-04-30 00:07:12.259355648,2016-05-03 23:06:58.571142912,55190.379428,229.858001,3.789574,0.156203,28.656896,2015.722233,7.809686,2.882329,3.958175,12.031393
min,1.000000,2014-01-03 00:00:00,2014-01-07 00:00:00,1040.000000,0.444000,1.000000,0.000000,-6599.978000,2014.000000,1.000000,1.000000,0.000000,-275.000000
25%,2499.250000,2015-05-23 00:00:00,2015-05-27 00:00:00,23223.000000,17.280000,2.000000,0.000000,1.728750,2015.000000,5.000000,2.000000,3.000000,7.500000
50%,4997.500000,2016-06-26 00:00:00,2016-06-29 00:00:00,56430.500000,54.490000,3.000000,0.200000,8.666500,2016.000000,9.000000,3.000000,4.000000,27.000000
75%,7495.750000,2017-05-14 00:00:00,2017-05-18 00:00:00,90008.000000,209.940000,5.000000,0.200000,29.364000,2017.000000,11.000000,4.000000,5.000000,36.250000
max,9994.000000,2017-12-30 00:00:00,2018-01-05 00:00:00,99301.000000,22638.480000,14.000000,0.800000,8399.976000,2017.000000,12.000000,4.000000,7.000000,50.000000
std,2885.163629,NaN,NaN,32063.693350,623.245101,2.225110,0.206452,234.260108,1.123555,3.284654,1.058086,1.747567,46.675435

In [27]:
#Missing Value Analysis
print("Missing Values Check")
print("="*60)

missing = df.isnull().sum()

missing_pct = (missing / len(df)) * 100

missing_df = pd.DataFrame({
    "Missing_Count": missing,
    "Missing_Percentage": missing_pct
})

missing_df = missing_df[missing_df["Missing_Count"] > 0]

if len(missing_df) > 0:
    print(missing_df)
else:
    print("No missing values found")

Missing Values Check
============================================================
No missing values found

In [28]:
#Duplicate Check
print("Duplicate Check")
print("="*60)

duplicates = df.duplicated().sum()

print(f"Total Duplicate Rows: {duplicates}")

if duplicates > 0:
    
    print(f"\nRemoving {duplicates} duplicate rows...")
    
    df = df.drop_duplicates()
    
    print("Duplicates removed successfully.")
    print(f"New Dataset Shape: {df.shape}")
    
else:
    
    print("No duplicate rows found")

Duplicate Check
============================================================
Total Duplicate Rows: 0
No duplicate rows found

In [29]:
#Data Type Conversion
print("Converting Date Columns")
print("="*60)

# Convert date columns to datetime format
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

print("Date columns successfully converted.\n")

print("Updated Data Types:")
print(df.dtypes)

Converting Date Columns
============================================================
Date columns successfully converted.

Updated Data Types:
Row ID                       int64
Order ID                    object
Order Date          datetime64[ns]
Ship Date           datetime64[ns]
Ship Mode                   object
Customer ID                 object
Customer Name               object
Segment                     object
Country                     object
City                        object
State                       object
Postal Code                  int64
Region                      object
Product ID                  object
Category                    object
Sub-Category                object
Product Name                object
Sales                      float64
Quantity                     int64
Discount                   float64
Profit                     float64
Order_Year                   int32
Order_Month                  int32
Order_Month_Name            object
Order_Quarter                int32
Order_Day                   object
Shipping_Days                int64
Profit_Margin              float64
Is_Profitable                 bool
dtype: object

# FEATURE ENGINEERING

In [30]:
print("Creating New Features")
print("="*60)

#Extract year & month from Order Date
df["Order_Year"] = df["Order Date"].dt.year
df["Order_Month"] = df["Order Date"].dt.month
df["Order_Month_Name"] = df["Order Date"].dt.strftime("%B")

#Quarter of order
df["Order_Quarter"] = df["Order Date"].dt.quarter

#Day of week
df["Order_Day"] = df["Order Date"].dt.day_name()

#Shipping duration
df["Shipping_Days"] = (df["Ship Date"] - df["Order Date"]).dt.days

#Profit Margin
df["Profit_Margin"] = (df["Profit"] / df["Sales"]) * 100

#Profitability flag
df["Is_Profitable"] = df["Profit"] > 0

print("New columns created successfully.\n")

print("New Dataset Shape:")
print(df.shape)

Creating New Features
============================================================
New columns created successfully.

New Dataset Shape:
(9994, 29)

In [31]:
#Checking Data Quality

print("Checking Data Quality")
print("="*60)

# Negative quantity check
negative_qty = df[df["Quantity"] < 0]
print(f"Negative Quantity Records: {len(negative_qty)}")

# Negative sales check
negative_sales = df[df["Sales"] < 0]
print(f"Negative Sales Records: {len(negative_sales)}")

# Ship date before order date
wrong_dates = df[df["Ship Date"] < df["Order Date"]]
print(f"Ship Date before Order Date: {len(wrong_dates)}")

print("\nProfitability Summary")

print(f"Profitable Orders: {df['Is_Profitable'].sum():,}")
print(f"Loss Orders: {(~df['Is_Profitable']).sum():,}")

Checking Data Quality
============================================================
Negative Quantity Records: 0
Negative Sales Records: 0
Ship Date before Order Date: 0

Profitability Summary
Profitable Orders: 8,058
Loss Orders: 1,936

In [23]:
#Save Cleaned Dataset
df.to_csv(
    r"E:\End to end sales data project\Data\Sample - superstore_cleaned.csv",
    index=False
)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.